### ISSUE TITLE
"Create Obj Controls" on mirrored skeletons aren't matching.

### ISSUE THREAD

**Issue by maxouhouh** [kamilhepner/kinefx_tools#1]
Hi, 
First of all thanks for this incredible library of tools. You've done a greate job!

I'm facing an issue with a mirrored skeleton by scale.
Everything seems ok in SOP level (controls are in the right place).
But when I apply your tool "Create Obj Controls", every controllers on the mirrored side are rotated by 180 degrees from the first joint.

The following screen shows the OBJ level generated controls (in yellow) an the SOP level controls of the mirrored side in blue.
![Screenshot 2021-03-22 023454](https://user-images.githubusercontent.com/49403440/111929631-394e1980-8ab7-11eb-82fc-c88a97aa9198.png)

The issue seem to be in the  create zero attr hda but I've no idea how to solve it.
Do you have an idea how to fix it?

Maxime B.

**Comment by kamilhepner** [comment]
Thanks, Maxime! I've looked at it and found out that's a bug 🐞 , currently only **rotation** base mirror is supported. I will let you know when it's fixed.

**Comment by kamilhepner** [comment]
Fixed in the latest commit. Please update your HDAs, also you can find handy to check video about the update: https://youtu.be/5WK1MC7MyQ8

**Comment by maxouhouh** [comment]
Hi Kamil!
Thanks for the update and the video!
I updated all my HDAs but I think the bug still remain. 

I checked your Attribute Wrangle (add_ZEROS) in the create zero attr and you're not using the scale parameter. Every call of this parameter are commented. Can the issues be related to this?

I joined a [screenshot](https://user-images.githubusercontent.com/49403440/112730592-b43d8700-8f32-11eb-84a8-257c6106dc55.png) of my Fks fingers controls (reds are sop level and yellow are OBJ levels) to show you.

Maxime B.

**Comment by kamilhepner** [comment]
Hi Maxime, so sorry for the late reply. Yes, your right attribute wrangle isn't using scale parameters, but that shouldn't be the issue. Could you send me a scene with that issue. Could be few things, and that will be easier to investigate. Also please let me know which version of Houdini you're using.

**Comment by kamilhepner** [comment]
Hi @maxouhouh I did few fixes today which could address your issue. Please check it out and let me know

**Comment by maxouhouh** [comment]
> Hi @maxouhouh I did few fixes today which could address your issue. Please check it out and let me know

Hi Kamil, sorry for the late reply, I was pretty busy last weeks.

I tried your scene file and It works perfectly. But I re-opened an older version of my rig and I wasn't able to make it work. 
At present, I have changed my scale method to rotation but maybe you would like to understand what I'm doing so that I don't have a correct mirror. So, here is a simple file if you want to check. I hope it can help.

[BugMirrorScale.zip](https://github.com/kamilhepner/kinefx_tools/files/6411804/BugMirrorScale.zip)

Thanks for the changes on the spaces too. I search and I made these changes locally a few days ago for the lack of speed of the timeshift method. You anticipated my request.

Maxime B.
